### ISSUE TITLE
PR?

### ISSUE THREAD

**Issue by eaCe** [alexplusde/bs5_iconpicker#1]
@alxndr-w wenn du möchtest kann ich einen PR erstellen: https://github.com/eaCe/bs5_iconpicker
Ein paar kleinere fixes. Etwas hacky...

**Comment by alxndr-w** [comment]
Hab dich zum Repo gefügt.

**Comment by eaCe** [comment]
Danke, aber ich will ja nicht einfach so in dein Repo commiten. Das musst du ja abnehmen :)

**Comment by alxndr-w** [comment]
Alles gut, du kannst darin arbeiten, einen PR machen, und mich reviewen lassen. Kannst aber auch in einem Fork lassen.

**Comment by eaCe** [comment]
Achso, also dann einen Branch erstellen? Klar kann ich beim nächsten Push so machen.
